### ISSUE TITLE
Enum API with newtypes

### ISSUE THREAD

**Issue by wmanley** [cberner/fuser#138]
This is a tracking issue for the work I've been doing on enum based API.

The goal is to have an easier to use, more decoupled, more typesafe, more extensible and better documented API than is possible in languages with less powerful type-systems. I believe by exploiting Rust's type-system we can create a much nicer API than is possible in C (libfuse) or golang. This means using enums, newtypes, the the typestate pattern, `?` based error handling, etc.

**TODO**

- [x] A type per request type #119 
- [ ] Document every request type #140
- [ ] Check each `u32`/`u64` in the API and decide if a newtype would be more appropriate - particularly around flags
- [x] #137
- [x] Response type #131
- [ ] Add `serve_sync()` API #136 
- [ ] Add `serve_async()` API
- [ ] Add `serve_multithreaded()` API
- [ ] Port https://github.com/wmanley/ostree-oxide/tree/master/ostree-fuse to see how it looks
- [ ] Refactor `Filesystem` trait API into a module?
- [ ] Use typestate pattern to encapsulate `Init`: https://github.com/cberner/fuser/issues/91#issuecomment-809283993
- [ ] Make enum API public #136

**Comment by cberner** [comment]
Closing due to inactivity, but feel free to re-open if you're still working on this.
